-- ==========================================
-- CREATE duplicate_leads TABLE
-- ==========================================
CREATE TABLE IF NOT EXISTS duplicate_leads (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT,
  phone TEXT,
  email TEXT,
  source TEXT,
  config TEXT,
  budget NUMERIC,
  message TEXT,
  duplicate_of BIGINT REFERENCES contacts(id) ON DELETE CASCADE,
  match_type TEXT,
  status TEXT DEFAULT 'pending',
  capture_data JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS Policies
ALTER TABLE duplicate_leads ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public inserts" ON duplicate_leads
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow authenticated read/update/delete" ON duplicate_leads
  FOR ALL USING (auth.role() = 'authenticated');
